version: '3.4'

volumes:
  van-price-service-data:
    name: "van-price-service-data"
    external: true

services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # The HTTP Port
      - "80:80"
      # The Web UI
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  van-price-service:
    image: van-price-service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    labels:
      - "traefik.http.routers.vanpriceservice.rule=Host(`PlanMyCamper.online`)"
    deploy:
      mode: replicated
      replicas: 3

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - van-price-service-data:/data/db
    ports:
      - 27017:27017
