version: '3.4'

volumes:
  van-price-service-data:
    name: "van-price-service-data"
    external: true

networks:
  van-price-service-network:
    name: "van-price-service-network"
    external: true

services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # The HTTP Port
      - "80:80"
      # The Web UI
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  van-price-service:
    image: van-price-service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    labels:
      - "traefik.http.routers.vanpriceservice.rule=Host(`PlanMyCamper.online`)"
    deploy:
      mode: replicated
      replicas: 3
    #Ensure mongo always starts first
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - van-price-service-network
    secrets:
      - db_connection_string
      - db_service_user_name
      - db_service_user_password

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - van-price-service-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    networks:
      - van-price-service-network
    secrets:
      - db_root_username
      - db_root_password
      - db_service_user_name
      - db_service_user_password

secrets:
  db_connection_string:
    file: run/secrets/db_connection_string
  db_root_username:
    file: run/secrets/db_root_username
  db_root_password:
    file: run/secrets/db_root_password
  db_service_user_name:
    file: run/secrets/db_service_user_name
  db_service_user_password:
    file: run/secrets/db_service_user_password
