version: '3.4'

services:
  reverse-proxy:
    image: traefic:v3.1
    command:
      - "--api-insecure:=true"
      - "--providers.docker"
    ports:
      # The HTTP Port
      - "80:80"
      # The application port
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  vanpriceservice:
    image: vanpriceservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
